export enum TaskStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export interface ProjectTask {
  id: string;
  title: string;
  prompt: string;
  goal: string;
  status: TaskStatus;
  result?: string; // Markdown content generated by AI
  errorMessage?: string; // Detailed error message for debugging
  createdAt: number;
}

export interface GeminiError {
  message: string;
}